### ISSUE TITLE
App crashes on Pixel 2 XL (API 27) emulator

### ISSUE THREAD

**Issue by ezanetta** [plivo/plivo-android-sdk2-examples#3]
Stacktrace:

E/linker: "/data/app/com.plivo.voicecalling-daUrp3wZNEzDb_zXhcyegg==/lib/x86/libpjplivo.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)

E/zygote: No implementation found for void com.plivo.endpoint.backend.plivoJNI.swig_module_init() (tried Java_com_plivo_endpoint_backend_plivoJNI_swig_1module_1init and Java_com_plivo_endpoint_backend_plivoJNI_swig_1module_1init__)

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.plivo.voicecalling, PID: 25999
    java.lang.UnsatisfiedLinkError: No implementation found for void com.plivo.endpoint.backend.plivoJNI.swig_module_init() (tried Java_com_plivo_endpoint_backend_plivoJNI_swig_1module_1init and Java_com_plivo_endpoint_backend_plivoJNI_swig_1module_1init__)
        at com.plivo.endpoint.backend.plivoJNI.swig_module_init(Native Method)
        at com.plivo.endpoint.backend.plivoJNI.<clinit>(plivoJNI.java:118)
        at com.plivo.endpoint.backend.plivoJNI.new_PlivoAppCallback(Native Method)
        at com.plivo.endpoint.backend.PlivoAppCallback.<init>(PlivoAppCallback.java:118)
        at com.plivo.endpoint.BackendListener.<init>(BackendListener.java:28)
        at com.plivo.endpoint.Endpoint.initLib(Endpoint.java:154)
        at com.plivo.endpoint.Endpoint.<init>(Endpoint.java:50)
        at com.plivo.voicecalling.Helpers.Phone.<init>(Phone.java:35)
        at com.plivo.voicecalling.Helpers.Phone.<clinit>(Phone.java:18)
        at com.plivo.voicecalling.Helpers.Phone.getInstance(Phone.java:28)
        at com.plivo.voicecalling.Activities.LoginActivity.onCreate(LoginActivity.java:62)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Screenshot: [https://imgur.com/a/zhdcVOX](https://imgur.com/a/zhdcVOX)

**Comment by eniyavan-muruganantham-plivo** [comment]
@ezanetta  Please try using our latest example application and write to https://support.plivo.com/ for any queries
